### ISSUE TITLE
Need more documentation

### ISSUE THREAD

**Issue by maikthulhu** [incidrthreat/goshorten#3]
To whom it may concern:

**Comment by incidrthreat** [comment]
What sort of documentation would you suggest? And in how much depth?

**Comment by maikthulhu** [comment]
A filled in readme 😁

**Comment by incidrthreat** [comment]
I've updated the README.  What additional info would you like to see there? What's lacking to explain the project or how to set it up?

**Comment by maikthulhu** [comment]
This issue was filed prior to the readme being completed. I was being cheeky and giving your more issues to close. Basically you should thank me. I'll await my reward.

**Comment by incidrthreat** [comment]
Haha, I thought there was more I forgot to include.  <3 Bourbon sticker on the way!
