### ISSUE TITLE
0 + 0 = 0

### ISSUE THREAD

**Issue by maikthulhu** [incidrthreat/goshorten#5]
incidr: `tries := 0`
also incidr: `for tries <3 { tries += tries }`

https://github.com/incidrthreat/goshorten/blob/8e3fc40756d2c8e6b8e6029493238f3fddd7245b/backend/data/redis.go#L86

But hey, at least you won't bof now!

**Comment by incidrthreat** [comment]
Solved: https://github.com/incidrthreat/goshorten/commit/43b21d947e137761668428307c9703f4412f4191

Thanks @maikthulhu!
